# Generated by Django 6.0.6 on 2026-06-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
    ]
